title: Smrithi S
logo: /assets/img/logo.png
description: Engineer Consultant@ISRO - VSSC
show_downloads: false
show_socialmedia: true
google_analytics:
theme: jekyll-theme-minimal
social_media:
  googlescholar: "https://scholar.google.com/citations?view_op=list_works&hl=en&authuser=1&user=MBnOhFsAAAAJ"
  github: "https://github.com/smrithis"
  linkedin: "https://www.linkedin.com/in/smrithi-siddagangaiah/"
