title: Smrithi
logo: /assets/img/logo.png
description: Thanks for finding my site, please feel free to take a tour :)
show_downloads: false
show_socialmedia: true
google_analytics:
theme: jekyll-theme-minimal
social_media:
  github: "https://github.com/smrithis"
  linkedin: "https://www.linkedin.com/in/smrithi-siddagangaiah/"
